### ISSUE TITLE
导出时报错：OpenXML4JRuntimeException

### ISSUE THREAD

**Issue by pangqibao** [liaochong/myexcel#120]
**Bug描述**
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /xl/worksheets/sheet1.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@3b5bafe2
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:558)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1488)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
	at com.github.liaochong.myexcel.utils.AttachmentExportUtil.export(AttachmentExportUtil.java:71)
	at com.ymtx.sudoku.comm.excel.CustomerGoodsExportCtrl.export(CustomerGoodsExportCtrl.java:64)
	at sun.reflect.GeneratedMethodAccessor1230.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at xorg.springboot.cors.CorsFilter.doFilter(CorsFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
就正常导出，报错以上异常

**期望的结果**
可以正常导出

**Comment by liaochong** [comment]
请提供下使用版本以及对应的导出代码，谢谢！

**Comment by pangqibao** [comment]
> 请提供下使用版本以及对应的导出代码，谢谢！

使用的版本是2.5.1 
导出代码
List<CustomerExImDto> exportList = getExportList();
            Workbook workbook = DefaultExcelBuilder.of(CustomerExImDto.class)
                    .build(exportList);
            AttachmentExportUtil.export(workbook, "CustomerExImDto", response);

**Comment by liaochong** [comment]
请先升级到最新版2.8.4看下问题是否可以得到解决

**Comment by pangqibao** [comment]
> 请先升级到最新版2.8.4看下问题是否可以得到解决

嗯嗯，刚刚升级了一下，先试试看吧

**Comment by liaochong** [comment]
请问是否解决？

**Comment by pangqibao** [comment]
> 请问是否解决？

暂时还不知道，需要多跑跑，过一段时间，2.5.1版本的时候也不是第一次就报错的

**Comment by liaochong** [comment]
需要注意的是，myexcel中所有的构建器均不可以用作单例

**Comment by pangqibao** [comment]
> 需要注意的是，myexcel中所有的构建器均不可以用作单例

嗯嗯，好的
