### ISSUE TITLE
myexcel-3.3.1本机导出正常，centos上导出异常。

### ISSUE THREAD

**Issue by leafleo** [liaochong/myexcel#181]
**Bug描述**
myexcel-3.3.1 动态导出在window开发机器正常，在生产机器导出异常。
开发机器：
1. window10
2. oracle jdk8
生产机器：
1. 操作系统：centos7.6
2. openjdk8

**异常如下：**
```
java.lang.NullPointerException: null
	at com.github.liaochong.myexcel.core.AbstractSimpleExcelBuilder.lambda$getFilteredFields$10(AbstractSimpleExcelBuilder.java:448)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.liaochong.myexcel.core.AbstractSimpleExcelBuilder.getFilteredFields(AbstractSimpleExcelBuilder.java:450)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.start(DefaultStreamExcelBuilder.java:270)
```

**代码：**
```
@ExcelTable(sheetName = "设备详情")
public class DeviceGeoLocationVo implements Serializable {
    @ExcelColumn(order=0, title = "设备编号")
    private Integer id;
    @ExcelColumn(order=1, title = "UUID")
    private String uuid;
    @ExcelColumn(order=2, title = "一级场景")
    private String parentName;// 一级场景名称
    @ExcelColumn(order=3, title = "二级场景名称")
    private String sceneName;// 二级场景名称
......
导出主要代码：
try (DefaultStreamExcelBuilder defaultExcelBuilder = DefaultStreamExcelBuilder
                    .of(DeviceGeoLocationVo.class)
                    .titles(titles)
                    .fieldDisplayOrder(order)
                    .threadPool(Executors.newFixedThreadPool(10))
                    .capacity(60_000)
                    .start()) {
                // 多线程异步获取数据并追加至excel，join等待线程执行完成
                complateableFutureSearchDevicePage(dto, total, defaultExcelBuilder);
                // 最终构建
                Path zip = defaultExcelBuilder.buildAsZip("geoLocationDevice"+System.currentTimeMillis());
                AttachmentExportUtil.export(zip, "地理位置详情.zip", resp);
                long endTime = System.currentTimeMillis() - btm;
                LOG.info("【" + total + "】条数据处理完毕，总耗时【" + endTime + "】ms");
                //删除
                //Files.delete(zip);
            } catch (IOException e) {
                LOG.error("导出地理位置信息出错：{}" + e.getMessage());
            }
```

**Comment by liaochong** [comment]
生产，请先降级为3.2.4，尽快排查原因，抱歉

**Comment by liaochong** [comment]
另外，请把全部的异常贴下，感谢

**Comment by liaochong** [comment]
使用@ExcelColumn(order=3, title = "二级场景名称")时，不需要调用这两个方法：
.titles(titles)
.fieldDisplayOrder(order)

**Comment by leafleo** [comment]
详情异常
java.lang.NullPointerException: null
	at com.github.liaochong.myexcel.core.AbstractSimpleExcelBuilder.lambda$getFilteredFields$10(AbstractSimpleExcelBuilder.java:448)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.liaochong.myexcel.core.AbstractSimpleExcelBuilder.getFilteredFields(AbstractSimpleExcelBuilder.java:450)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.start(DefaultStreamExcelBuilder.java:270)
	at com.buss.device.v2.service.impl.DeviceSearchServiceImpl.poiExp(DeviceSearchServiceImpl.java:188)
	at com.buss.device.v2.controller.DeviceExportV2Controller.poiExport(DeviceExportV2Controller.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.spring.boot.starter.web.filter.AbstractValidateRequestFilter.doFilter(AbstractValidateRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.spring.boot.starter.web.filter.HeaderFilter.doFilter(HeaderFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.spring.boot.starter.web.filter.LogRequestFilter.doFilter(LogRequestFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


> 使用@ExcelColumn(order=3, title = "二级场景名称")时，不需要调用这两个方法：
> .titles(titles)
> .fieldDisplayOrder(order)
在本地开发机器上不使用@ExcelColumn注解，本来我们业务是页面可以动态选择表头导出的，下述代码段出现空指针异常。
 preElectionFields = preElectionFields.stream()
                    .filter(field -> !Modifier.isStatic(field.getModifiers()))
                    .collect(Collectors.toList());

**Comment by liaochong** [comment]
按照异常跟踪了下代码
preElectionFields = preElectionFields.stream()
.filter(field -> !Modifier.isStatic(field.getModifiers()))
.collect(Collectors.toList());

preElectionFields这部分不可能为空，按理来说不应该出现空指针问题，本地按你提供的代码测试也无法重现，可能是缺乏对应的有效数据，能否麻烦你断点截图看下具体是哪里出现空指针呢？

**Comment by liaochong** [comment]
相同的数据？

**Comment by leafleo** [comment]
完全相同的字段与数据，在生产上把动态字段注掉使用，就可以正常导出,暂时去掉页面上动态选择字段导出功能。
.titles(titles)
.fieldDisplayOrder(order)

**Comment by liaochong** [comment]
预发环境能重现吗？如果能，预发环境是否可以断点呢？如果都不允许的话，只能clone一份代码，修改版本号，deploy到私服上，然后在抛异常的地方添加一定的日志查看

**Comment by leafleo** [comment]
好的，有空折腾下。谢谢！暂时无法定位，我把issue关闭先。
