### ISSUE TITLE
Date类型的参数 加上 @ExcelColumn(order = 1, format = "yyyy-MM-dd HH:mm:ss", defaultValue = "/") 导出会报 ClassCastException 错误

### ISSUE THREAD

**Issue by wanderhero** [liaochong/myexcel#196]
操作如 title 所示
看了下，会在 AbstractSimpleExcelBuilder 这个类的 setTdContent 里拿到了默认值去转 Data 类型导致报错

**Comment by liaochong** [comment]
请提供下版本以及异常栈，谢谢

**Comment by liaochong** [comment]
defaultValue是设计用来在字段值为null时，默认填充的字符串，按您的错误提示，应该是返回的TdContent的类型错误，应该是String，能否帮忙修改该问题提交一个PR呢？另外，3.4.0版本后，默认时间全局格式化为yyyy-MM-dd HH:mm:ss，所以字段上是可以不标明该格式化的

**Comment by wanderhero** [comment]
版本是 release-3.4.0.RELEASE，但是从 3.2.4 以后应该都有这个问题，我一直在用MyExcel，还是非常感谢

用 默认导出 就会报错，关键参数是 
@ExcelColumn(order = 1, defaultValue = "/")
private Date cc;

异常错误如下
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
	at com.github.liaochong.myexcel.core.DefaultExcelBuilder.build(DefaultExcelBuilder.java:164)
	at com.daoism.web.modules.test.controller.TestExcelController.buildDefault(TestExcelController.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

我能想到的办法是 
try catch ClassCastException，直接设置为 String ，不知道对你的代码会不会有影响，你可以考虑下
td.setContent(String.valueOf(pair.getValue()));

**Comment by liaochong** [comment]
非常感谢，getRenderContent方法使用默认值时，Pair.of(field.getType(), defaultValue)的类型错误了，应该是Pair.of(String.class, defaultValue)，能帮忙clone下分支然后修复提交PR嘛，因为是你发现的，还是比较希望能够在代码上添加上修复者的姓名以及记录贡献者

**Comment by liaochong** [comment]
3.4.1已发布，预计2020/02/21可用，感谢！！！

**Comment by wanderhero** [comment]
响应非常迅速，点赞~
