### ISSUE TITLE
导入功能有 某个单元格有图片解析出null

### ISSUE THREAD

**Issue by VcZint** [liaochong/myexcel#200]
依赖 <groupId>com.github.liaochong</groupId>
            <artifactId>myexcel</artifactId>
            <version>3.3.0.GA</version>

实体类
@ExcelColumn(index=19)
	InputStream picture;

debug结果： picture=null

（excel表格插入的图片嵌入单元格和浮动图片识别都为null）

**Comment by liaochong** [comment]
请提供下代码，需要注意的是，仅有DefaultExcelReader可以导入图片，SaxExcelReader暂不支持

**Comment by VcZint** [comment]
list = DefaultExcelReader.of(clazz)
				// 0代表第一个，如果为0，可省略该操作，也可sheet("名称")读取
				.sheet(0)
				// 如无需过滤，可省略该操作，0代表第一行
				.rowFilter(row -> row.getRowNum() > 0 && row.getCell(0).getCellType() != 3)
				// 可接收inputStream
				.read(file.getInputStream());

都是官网上抄的。。

**Comment by VcZint** [comment]
其他数据可以正常解析  唯独图片不行

**Comment by VcZint** [comment]
还有今天遇上一个奇怪的事   xls文件在.rowFilter这一行报空指针无法解析  又新建了个xlsx将内容复制进去就可以正常解析了

**Comment by liaochong** [comment]
能不能把你遇到问题的两份excel发我下呢？

**Comment by VcZint** [comment]
[新建文件夹.zip](https://github.com/liaochong/myexcel/files/4236156/default.zip)

**Comment by liaochong** [comment]
收到，会尽快核实问题

**Comment by VcZint** [comment]
无法解压还是里面文件打不开

**Comment by liaochong** [comment]
无法解压

**Comment by VcZint** [comment]
已经发您邮箱一份

**Comment by liaochong** [comment]
打开文件不存在有效图片
![image](https://user-images.githubusercontent.com/8674986/75040367-7da66900-54f5-11ea-9b41-dc70730affb1.png)

**Comment by VcZint** [comment]
最后一列放图片  什么图片都无法识别

**Comment by liaochong** [comment]
两个问题：
1.图片问题，excel需要有有效图片，方可读取；
2..xls读取空指针问题，使用最新版3.4.1读取正常，请切换为3.4.1版本

**Comment by VcZint** [comment]
麻烦您帮忙放个图片发给我一份可以吗  我也怀疑图片没放进去所以没读取到

**Comment by liaochong** [comment]
已发送邮箱

**Comment by liaochong** [comment]
3.4.1版本验证无上述问题，请升级后验证

**Comment by VcZint** [comment]
切换到3.4.1后正常  谢谢拉

**Comment by VcZint** [comment]
您好，请问一下在3.4.1版本 假如excel表格中有BigDecimal格式的数值 ，现在解析中会有
异常，请问支持这种格式吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清沐"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上10:12
收件人:&nbsp;"liaochong/myexcel"<myexcel@noreply.github.com&gt;;
抄送:&nbsp;"匣与桔"<784243429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liaochong/myexcel] 导入功能有 某个单元格有图片解析出null (#200)




两个问题：
 1.图片问题，excel需要有有效图片，方可读取；
 2..xls读取空指针问题，使用最新版3.4.1 读取正常，请切换为3.4.1版本

**Comment by liaochong** [comment]
支持的，请提供下具体数值，以及异常

**Comment by VcZint** [comment]
异常&nbsp; 2020-03-10 11:10:28.811 ERROR 19576 --- [&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;task-4] o.b.c.r.listener.ReportTaskListener&nbsp; &nbsp; &nbsp; : report task execute fail,event:org.bootybay.core.report.event.ReportTaskEvent[source=ImportTaskEvent(t=TruckVO(ids=null, relationId=null, truckDescription=null, mainDriver=null, mainDriverStatus=null, mainDriverStatusName=null, statusName=null, flag=0, nameDriver=null, vehicleTypeName=null, powerTypeName=null, placeName=null, truckPhotos=null, otherPhotos=null, truckLengthStart=null, truckLengthEnd=null, truckWeightStart=null, truckWeightEnd=null, axleList=null, vehicleTypeList=null, allPhotos=null, applyStartTime=null, applyEndTime=null, truckLicensePhoto=null, transportLicensePicture=null), taskId=1237214209348059137, url=https://jiaoyi95.oss-cn-beijing.aliyuncs.com/车辆批量导入.xlsx, firstRowValidator=org.bootybay.system.controller.PortalTruckController$$Lambda$1001/102356428@39ccc8, valueMapper=org.bootybay.system.controller.PortalTruckController$$Lambda$1002/605974087@6db91c23, func=org.bootybay.system.controller.PortalTruckController$$Lambda$1003/1917838881@6209263e)],error:com.github.liaochong.myexcel.exception.ExcelReadException: Failed to convert content,field:[axle],content:[山东],rowNum:[1]
	at com.github.liaochong.myexcel.core.converter.ReadConverterContext.convert(ReadConverterContext.java:133)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.lambda$instanceObj$10(DefaultExcelReader.java:440)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.instanceObj(DefaultExcelReader.java:425)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.readThenConsume(DefaultExcelReader.java:368)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.readThen(DefaultExcelReader.java:205)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.readThen(DefaultExcelReader.java:195)
	at org.bootybay.core.report.listener.ReportTaskListener.onReport(ReportTaskListener.java:72)
	at org.bootybay.core.report.listener.ReportTaskListener$$FastClassBySpringCGLIB$$853fd0b.invoke(<generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.bootybay.core.log.aspect.LogTraceAspect.around(LogTraceAspect.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init&gt;(BigDecimal.java:494)
	at java.math.BigDecimal.<init&gt;(BigDecimal.java:383)
	at java.math.BigDecimal.<init&gt;(BigDecimal.java:806)
	at com.github.liaochong.myexcel.core.converter.reader.NumberReadConverter.doConvert(NumberReadConverter.java:53)
	at com.github.liaochong.myexcel.core.converter.reader.NumberReadConverter.doConvert(NumberReadConverter.java:32)
	at com.github.liaochong.myexcel.core.converter.reader.AbstractReadConverter.convert(AbstractReadConverter.java:73)
	at com.github.liaochong.myexcel.core.converter.reader.AbstractReadConverter.convert(AbstractReadConverter.java:40)
	at com.github.liaochong.myexcel.core.converter.ReadConverterContext.convert(ReadConverterContext.java:129)
	... 28 more








============================================
excel：https://jiaoyi95.oss-cn-beijing.aliyuncs.com/%E8%BD%A6%E8%BE%86%E6%89%B9%E9%87%8F%E5%AF%BC%E5%85%A5.xlsx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清沐"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 中午12:25
收件人:&nbsp;"liaochong/myexcel"<myexcel@noreply.github.com&gt;;
抄送:&nbsp;"匣与桔"<784243429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liaochong/myexcel] 导入功能有 某个单元格有图片解析出null (#200)




支持的，请提供下具体数值，以及异常

**Comment by liaochong** [comment]
![image](https://user-images.githubusercontent.com/8674986/76279867-25c87a00-62cb-11ea-8fe1-6896c9dc2932.png)
异常表明，axle这个字段无法设置为“山东”值，请确认该字段对应的列是否正确

**Comment by VcZint** [comment]
您好，现在我这边有一个问题：eventListener导出文件
代码：
-------------------event----------
public class ExportTaskEvent extends ApplicationEvent {

   public ExportTaskEvent(ExportTask source) {
      super(source);
   }

}
---------listener--------------
@Async
@Order
@EventListener(ExportTaskEvent.class)
public <T&gt; void onReport(ExportTaskEvent taskEvent) {
   Long taskId = 0L;
   try {
      ExportTask event = (ExportTask) taskEvent.getSource();
      taskId =  event.getTaskId();

      // 1.导出excel
      List list = event.getTs();
      Workbook workbook = DefaultExcelBuilder.of(list.get(0).getClass()).build(list);
      AttachmentExportUtil.export(workbook, event.getExportFileName(), event.getResponse());

      // 2. 最后将任务置为成功
      iReportTaskClient.update(ReportTask.builder()
         .id(taskId)
         .status(ReportTaskStatus.SUCCESS.getValue())
         .result("导出数据成功：一共处理" + list.size() + "个")
         .build());
   } catch (Exception e) {
      taskFail(taskId, "数据导出错误，请查看数据信息");
      log.error("report task execute fail,event:{},error:{}", taskEvent, Throwables.getStackTraceAsString(e));
   }
}



===================================
现在问题是可以进入event，但是在listener上的断电都进不去


报错：


error:org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@2688d1ed
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:558)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1505)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
	at com.github.liaochong.myexcel.utils.AttachmentExportUtil.export(AttachmentExportUtil.java:73)
	at org.bootybay.core.report.listener.ExportTaskListener.onReport(ExportTaskListener.java:41)
	at org.bootybay.core.report.listener.ExportTaskListener$$FastClassBySpringCGLIB$$986fb8b.invoke(<generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.bootybay.core.log.aspect.LogTraceAspect.around(LogTraceAspect.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@2688d1ed
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:547)
	... 26 more











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清沐"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 中午12:33
收件人:&nbsp;"liaochong/myexcel"<myexcel@noreply.github.com&gt;;
抄送:&nbsp;"匣与桔"<784243429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liaochong/myexcel] 导出功能

**Comment by liaochong** [comment]
我看你导出是异步的，response流应该已经关闭了，会导致导出失败
