### ISSUE TITLE
wiki improvement double freemarker NumberFormatException

### ISSUE THREAD

**Issue by kortov** [liaochong/myexcel#213]
Hi, I stumbled upon an issue, when I got big double values (more that a 1000), I've got an exception

```java
ERROR com.github.liaochong.myexcel.exception.ExcelBuildException: Failed to build excel
	at com.github.liaochong.myexcel.exception.ExcelBuildException.of(ExcelBuildException.java:33)
	at com.github.liaochong.myexcel.core.AbstractExcelBuilder.build(AbstractExcelBuilder.java:94)
Caused by: java.lang.NumberFormatException: For input string: "1 01828"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createCell(AbstractExcelFactory.java:241)
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createRow(AbstractExcelFactory.java:191)
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.setTdOfTable(HtmlToExcelFactory.java:205)
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.build(HtmlToExcelFactory.java:182)
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.build(HtmlToExcelFactory.java:131)
	at com.github.liaochong.myexcel.core.AbstractExcelBuilder.build(AbstractExcelBuilder.java:92)
	... 5 more 
```

So when value was 1018,28002929687 , freemarker printed 1 01828 to a document, and I've got an exception. Actually it's a freemarker issue, I should have used `${x?c}` value [freemarker doc](https://freemarker.apache.org/docs/ref_builtins_number.html#ref_builtin_c)

maybe add some info about it in the [wiki](https://github.com/liaochong/myexcel/wiki/%E5%8D%95%E5%85%83%E6%A0%BC%E8%AE%BE%E7%BD%AE) ? But it's only freemarker issue, if you won't fix it, you can close this issue, it's just be here for helping somebody

**Comment by liaochong** [comment]
Thank you very much for your reminding. I will put this issue on Wiki to help other users solve similar problems.

**Comment by liaochong** [comment]
The issue has been added to the FAQ.
