### ISSUE TITLE
XSSFSimpleShape cannot be cast to org.apache.poi.xssf.usermodel.XSSFPicture

### ISSUE THREAD

**Issue by jiangbingi** [liaochong/myexcel#260]
**Bug描述**
描述Bug产生的现象（A clear and concise description of what the bug is.）
普通默认导入包含矩形形状表格时出错

**堆栈信息**
Caused by: java.lang.ClassCastException: org.apache.poi.xssf.usermodel.XSSFSimpleShape cannot be cast to org.apache.poi.xssf.usermodel.XSSFPicture
	at com.github.liaochong.myexcel.core.DefaultExcelReader.lambda$getAllPictures$6(DefaultExcelReader.java:392) ~[myexcel-3.9.1.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_202]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_202]
	at com.github.liaochong.myexcel.core.DefaultExcelReader.getAllPictures(DefaultExcelReader.java:393) ~[myexcel-3.9.1.jar:na]
	at com.github.liaochong.myexcel.core.DefaultExcelReader.getSheet(DefaultExcelReader.java:304) ~[myexcel-3.9.1.jar:na]
	at com.github.liaochong.myexcel.core.DefaultExcelReader.getSheetOfInputStream(DefaultExcelReader.java:282) ~[myexcel-3.9.1.jar:na]
	at com.github.liaochong.myexcel.core.DefaultExcelReader.readThen(DefaultExcelReader.java:204) ~[myexcel-3.9.1.jar:na]
	at com.github.liaochong.myexcel.core.DefaultExcelReader.readThen(DefaultExcelReader.java:195) ~[myexcel-3.9.1.jar:na]
	at com.jsl.minimall.endpoint.admin.AdminEndpointFacade.importExcelProductData(AdminEndpointFacade.java:52) ~[classes/:na]
	... 71 common frames omitted

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）
看情况时是但是代码在获取所有图片的时候把所有Shape强转成XSSFPicture，实际上是XSSFSimpleShape，强制失败

**Comment by liaochong** [comment]
能否提供下原文件，方便测试重现，谢谢

**Comment by jiangbingi** [comment]
版本：3.9.1

> 
[商品模板.xlsx](https://github.com/liaochong/myexcel/files/4964903/default.xlsx)

**Comment by jiangbingi** [comment]
请问大概什么时候能发个版，最近准备上生产，目前我是自己修改打成私有jar，但是不方便

**Comment by liaochong** [comment]
预计今晚发布，能否请你push一下你的修改到master，确认下本次发布没有其他问题

**Comment by liaochong** [comment]
3.9.2已发布

**Comment by jiangbingi** [comment]
OK，没问题了
