### ISSUE TITLE
模板导出图片错误

### ISSUE THREAD

**Issue by hunshikan** [liaochong/myexcel#318]
**Bug描述**
数据map里面写的图片全路径
product.put("productImg", "http://127.0.0.1:8080/images/cover.png");
导出时报错信息如下
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http:\127.0.0.1:8080\images\cover.png
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:1.8.0_201]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:1.8.0_201]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:1.8.0_201]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[na:1.8.0_201]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[na:1.8.0_201]
	at java.io.File.toPath(File.java:2234) ~[na:1.8.0_201]
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.setImage(AbstractExcelFactory.java:408) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createCell(AbstractExcelFactory.java:315) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createRow(AbstractExcelFactory.java:217) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.setTdOfTable(HtmlToExcelFactory.java:249) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.buildTablesWithMultiSheet(HtmlToExcelFactory.java:195) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.build(HtmlToExcelFactory.java:169) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.HtmlToExcelFactory.build(HtmlToExcelFactory.java:129) ~[myexcel-3.11.4.jar:na]
	at com.github.liaochong.myexcel.core.AbstractExcelBuilder.build(AbstractExcelBuilder.java:97) ~[myexcel-3.11.4.jar:na]

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:

**期望的结果**
期望的结果是什么（A clear and concise description of what you expected to happen.）

**Comment by liaochong** [comment]
当前只支持物理绝对路径，如F://xx.jpg导出，还不支持其他协议，如http图片导出

**Comment by liaochong** [comment]
4.1.0版本修复
