### ISSUE TITLE
JDK 18 下读取Excel文件报错 com.github.liaochong.myexcel.core.cache.StringsCache

### ISSUE THREAD

**Issue by 0604hx** [liaochong/myexcel#373]
**Bug描述**

```text
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.liaochong.myexcel.core.cache.StringsCache
    at com.github.liaochong.myexcel.core.SaxExcelReader.process(SaxExcelReader.java:252)
    at com.github.liaochong.myexcel.core.SaxExcelReader.doReadXlsx(SaxExcelReader.java:226)
    at com.github.liaochong.myexcel.core.SaxExcelReader.doRead(SaxExcelReader.java:201)
    ... 69 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessError: class com.github.liaochong.myexcel.core.cache.StringsCache (in unnamed module @0x46d56d67) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x46d56d67
    at com.github.liaochong.myexcel.core.cache.StringsCache.<clinit>(StringsCache.java:73)
```

在读取 Excel 文件时出现上述错误，代码如下：

```java
SaxExcelReader.of(Personal.class)
                .sheet(0)
                .read(new File(filePath))
```

**Bug复现**

* 服务器：RedHat 7.9
* JAVA 版本：openJDK 18
* myexcel 版本：3.9.5

**期望的结果**

能够兼容最新的 JDK 版本

感谢！

**Comment by liaochong** [comment]
本周会发布一个新版本支持高版本jdk，感谢使用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 集成显卡 ***@***.***&gt;
发送时间: 2022年7月15日 17:37
收件人: liaochong/myexcel ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liaochong/myexcel] JDK 18 下读取Excel文件报错 com.github.liaochong.myexcel.core.cache.StringsCache (Issue #373)

**Comment by liaochong** [comment]
4.2.1版本已发布，支持高版本jdk
