### ISSUE TITLE
使用DefaultExcelReader导入遇到错误时报java.lang.NullPointerException

### ISSUE THREAD

**Issue by fcmfcm01** [liaochong/myexcel#419]
**Bug描述**
**版本：4.5.0**
`com.github.liaochong.myexcel.core.context.ReadContext#readConfig` 未初始化，导致当Excel导入时对错误信息的处理失败。

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
1. 按照导入示例准备一份导入数据和POJO，其中导入数据中存在数字转换异常，例如，POJO中`a` 变量为Double型，数据中对应列数据为“字符”
2. 使用`DefaultExcelReader`，导入刚才的数据， 得到下面的异常：
```java
java.lang.NullPointerException: null
	at com.github.liaochong.myexcel.core.converter.ReadConverterContext.convert(ReadConverterContext.java:149)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.lambda$instanceObj$18(DefaultExcelReader.java:432)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.instanceObj(DefaultExcelReader.java:417)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.getDataFromFile(DefaultExcelReader.java:329)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.doRead(DefaultExcelReader.java:202)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.read(DefaultExcelReader.java:183)
	at com.github.liaochong.myexcel.core.DefaultExcelReader.read(DefaultExcelReader.java:179)
```

**期望的结果**
Boolean toContinue = readContext.readConfig.exceptionFunction.apply(e, readContext); 语句能够正常执行

**Comment by liaochong** [comment]
请提供下版本，另外如果不导入图片，建议使用SaxExcelReader

**Comment by prosejazz** [comment]
我遇到了同样的问题，版本4.5.0，我这里是需要导入图片的
我看了看源码，似乎没有把exceptionFunction绑定到readContext.readConfig上

**Comment by liaochong** [comment]
@prosejazz 4.5.4版本修复
