### ISSUE TITLE
流式导出经常性出现异常，导不出

### ISSUE THREAD

**Issue by 18270704097** [liaochong/myexcel#430]
有时候日志显示这个错误
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Received a termination command
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
		at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:608)
		at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1500)
		at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:474)
		at org.apache.poi.ooxml.POIXMLDocument.close(POIXMLDocument.java:189)
		at org.apache.poi.xssf.usermodel.XSSFWorkbook.close(XSSFWorkbook.java:617)
		at org.apache.poi.xssf.streaming.SXSSFWorkbook.close(SXSSFWorkbook.java:927)
		at com.github.liaochong.myexcel.core.AbstractExcelFactory.closeWorkbook(AbstractExcelFactory.java:818)
		at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.clear(HtmlToExcelStreamFactory.java:428)
		at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.close(DefaultStreamExcelBuilder.java:453)
		at tech.yulang.logistics.lms.transportation.consignment.controller.ConsignmentController.export(ConsignmentController.java:81)
		at jdk.internal.reflect.GeneratedMethodAccessor2119.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)

有时候显示的是下面这个
java.lang.IllegalStateException: Cannot add merged region O3:O8 to sheet because it overlaps with an existing merged region (O2:O7).
	at org.apache.poi.xssf.usermodel.XSSFSheet.validateMergedRegions(XSSFSheet.java:429)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:349)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:303)
	at org.apache.poi.xssf.streaming.SXSSFSheet.addMergedRegion(SXSSFSheet.java:396)
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createCell(AbstractExcelFactory.java:376)
	at com.github.liaochong.myexcel.core.AbstractExcelFactory.createRow(AbstractExcelFactory.java:260)
	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.appendRow(HtmlToExcelStreamFactory.java:392)
	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.receive(HtmlToExcelStreamFactory.java:182)
	at java.base/java.lang.Thread.run(Thread.java:840)

出现错误之后开始就一直导不出来了，但是如果只导一条数据就可以导出，导超过2条及以上的数据就会出现以上的错误

**Comment by 18270704097** [comment]
版本：4.3.3

**Comment by liaochong** [comment]
请提供下导出代码以及导出数据

**Comment by 18270704097** [comment]
导出的代码
try (DefaultStreamExcelBuilder<ConsignmentView> defaultExcelBuilder = DefaultStreamExcelBuilder
                .of(ConsignmentView.class)
                .threadPool(Executors.newFixedThreadPool(15))
                .start()) {
            for (List<ConsignmentView> content : ListUtils.partition(contents, 1000)) {
                // 数据追加
                defaultExcelBuilder.asyncAppend(() -> content);
            }

            Workbook workbook = defaultExcelBuilder.build();

            AttachmentV2ExportUtil.export(workbook, "运单", response);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }

**Comment by liaochong** [comment]
不要用异步导出，直接用append 试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyyyy ***@***.***&gt;
发送时间: 2024年10月23日 09:53
收件人: liaochong/myexcel ***@***.***&gt;
抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [liaochong/myexcel] 流式导出经常性出现异常，导不出 (Issue #430)





 
导出的代码
 try (DefaultStreamExcelBuilder defaultExcelBuilder = DefaultStreamExcelBuilder
 .of(ConsignmentView.class)
 .threadPool(Executors.newFixedThreadPool(15))
 .start()) {
 for (List content : ListUtils.partition(contents, 1000)) {
 // 数据追加
 defaultExcelBuilder.asyncAppend(() -&gt; content);
 }
         Workbook workbook = defaultExcelBuilder.build();         AttachmentV2ExportUtil.export(workbook, "运单", response);     } catch (IOException e) {         throw new UncheckedIOException(e);     }

**Comment by 18270704097** [comment]
[需要导出的数据.xlsx](https://github.com/user-attachments/files/17484040/default.xlsx)

**Comment by 18270704097** [comment]
> 不要用异步导出，直接用append 试试 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: yyyyy ***@***.***&gt; 发送时间: 2024年10月23日 09:53 收件人: liaochong/myexcel ***@***.***&gt; 抄送: 清沐 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [liaochong/myexcel] 流式导出经常性出现异常，导不出 (Issue #430) 导出的代码 try (DefaultStreamExcelBuilder defaultExcelBuilder = DefaultStreamExcelBuilder .of(ConsignmentView.class) .threadPool(Executors.newFixedThreadPool(15)) .start()) { for (List content : ListUtils.partition(contents, 1000)) { // 数据追加 defaultExcelBuilder.asyncAppend(() -&gt; content); } Workbook workbook = defaultExcelBuilder.build(); AttachmentV2ExportUtil.export(workbook, "运单", response); } catch (IOException e) { throw new UncheckedIOException(e); } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我试试

**Comment by 18270704097** [comment]
还是不行，又出现上面的错误提示了

**Comment by 18270704097** [comment]
到今天又可以正常导出了，就是偶尔会出现的

**Comment by 18270704097** [comment]
有测试出来吗？我猜测是不是有什么流没有进行关闭处理啊，因为每次出现这些问题之后，我重启一下服务，就可以正常导出了，但是还是会再次出现

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by liaochong** [comment]
请升级至4.5.6
