### ISSUE TITLE
DefaultExcelBuilder 方法导出异常

### ISSUE THREAD

**Issue by 18270704097** [liaochong/myexcel#433]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Received a termination command
	at com.github.liaochong.myexcel.core.DefaultExcelBuilder.build(DefaultExcelBuilder.java:173)
	at tech.yulang.logistics.lms.transportation.consignment.controller.ConsignmentController.export(ConsignmentController.java:84)
	... 127 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Received a termination command
	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.append(HtmlToExcelStreamFactory.java:135)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.appendTr(DefaultStreamExcelBuilder.java:393)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.append(DefaultStreamExcelBuilder.java:387)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.append(DefaultStreamExcelBuilder.java:361)
	at com.github.liaochong.myexcel.core.DefaultExcelBuilder.build(DefaultExcelBuilder.java:164)
	... 128 common frames omitted

版本：4.5.3

![image](https://github.com/user-attachments/assets/7f617fde-710e-4c32-832a-f6a138dde3c1)
这里是什么条件下会发生的异常

**Comment by liaochong** [comment]
因为myexcel是采用生产者消费者模式导出，所以生产和消费并不同步，这个错误是在你append时，导出发生了其他异常而无法正常处理新append数据报的异常，通常你需要关注上一个异常

**Comment by 18270704097** [comment]
![image](https://github.com/user-attachments/assets/fd8f5580-a854-4dc8-9e67-bd62c5b3c143)
![image](https://github.com/user-attachments/assets/e3c5a7de-9fc4-40c1-acbc-7221cfb10a7d)
zheli这里是上一个异常

**Comment by 18270704097** [comment]
![image](https://github.com/user-attachments/assets/20438e69-bab4-4b29-8851-d886fea868db)
我这个导出对象也没有设置合并

**Comment by liaochong** [comment]
这是必现吗？能否升级到4.5.4看下问题是否仍然存在？

**Comment by liaochong** [comment]
请升级至4.5.6

**Comment by yyyyyjg** [comment]
> 这是必现吗？能否升级到4.5.4看下问题是否仍然存在？

不能说是必现吧，我每次重启系统服务，刚开始能用

**Comment by yyyyyjg** [comment]
过了一会或者说一天后用的人多了就开始出现这种错误了

**Comment by liaochong** [comment]
@18270704097 请升级到4.5.6，这是使用了mapping缓存导致的错误，新版本已解决

**Comment by yyyyyjg** [comment]
> @18270704097 请升级到4.5.6，这是使用了mapping缓存导致的错误，新版本已解决

<img width="1280" alt="6c24606c2b717dbb65b1031d4d8b931" src="https://github.com/user-attachments/assets/cf738710-e31f-4533-bced-bfef77b01481">
升级到 4.5.6 了，但是导入功能好像受到影响了，我现在回退版本回去了

**Comment by liaochong** [comment]
@18270704097 需要升级commons-io版本或者你把poi版本降级到5.2.5
