### ISSUE TITLE
DefaultStreamExcelBuilder 导出问题

### ISSUE THREAD

**Issue by yyyyyjg** [liaochong/myexcel#437]
DefaultStreamExcelBuilder 导出问题
在导出数量在200条左右，或者大于200条以上的时候，导出异常，小于200条左右就能正常导出，导出错误提示信息如下：

[ERROR] [2024-12-26 10:28:55.709] ForkJoinPool.commonPool-worker-1 com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.append：134
Received a termination command,an exception occurred while processing

[ERROR] [2024-12-26 10:28:55.824] XNIO-1 task-2 tech.yulang.logistics.lms.config.GlobalExceptionHandler.handleGlobal：41
异常: java.lang.UnsupportedOperationException: Received a termination command

java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Received a termination command
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: Received a termination command
	at com.github.liaochong.myexcel.core.HtmlToExcelStreamFactory.append(HtmlToExcelStreamFactory.java:135)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.appendTr(DefaultStreamExcelBuilder.java:393)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.append(DefaultStreamExcelBuilder.java:383)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.append(DefaultStreamExcelBuilder.java:361)
	at com.github.liaochong.myexcel.core.DefaultStreamExcelBuilder.lambda$asyncAppend$2(DefaultStreamExcelBuilder.java:410)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 common frames omitted

版本号：4.5.6

**Comment by yyyyyjg** [comment]
![image](https://github.com/user-attachments/assets/66f39fa6-44bb-412d-ab59-42cf8b06c866)
导出方法

**Comment by liaochong** [comment]
不要用asyncAppend方法，请尝试直接用append，asyncAppend存在问题，即将被删除
