### ISSUE TITLE
导出的时候报错：Broken pipe

### ISSUE THREAD

**Issue by pangqibao** [liaochong/myexcel#84]
**Bug描述**
导出之后就报错，不过数据是导出了的，但是后台紧接这就报错了

**Bug复现**
按如下步骤复现（Steps to reproduce the behavior）:
2019-06-18T07:15:13.709405182Z 2019-06-18 15:15:13,706 ERROR [http-nio-8604-exec-9] c.y.s.comm.common.GgExceptionHandler: org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/core.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@37f1f548
2019-06-18T07:15:13.709444370Z org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/core.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@37f1f548
2019-06-18T07:15:13.709600815Z 	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:558)
2019-06-18T07:15:13.709628501Z 	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1488)
2019-06-18T07:15:13.709641736Z 	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
2019-06-18T07:15:13.709654764Z 	at com.github.liaochong.myexcel.utils.AttachmentExportUtil.export(AttachmentExportUtil.java:71)
2019-06-18T07:15:13.709667572Z 	at com.ymtx.sudoku.comm.excel.PriceAdjustGoodsExportCtrl.export(PriceAdjustGoodsExportCtrl.java:35)
2019-06-18T07:15:13.710441229Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-06-18T07:15:13.710459568Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-06-18T07:15:13.710472853Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-06-18T07:15:13.710512326Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-06-18T07:15:13.710527542Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2019-06-18T07:15:13.710540568Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
2019-06-18T07:15:13.710553505Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
2019-06-18T07:15:13.710566842Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
2019-06-18T07:15:13.710580091Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
2019-06-18T07:15:13.710597786Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
2019-06-18T07:15:13.710612486Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
2019-06-18T07:15:13.710625366Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
2019-06-18T07:15:13.710637732Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
2019-06-18T07:15:13.710650590Z 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
2019-06-18T07:15:13.710663764Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
2019-06-18T07:15:13.710676412Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
2019-06-18T07:15:13.710688758Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
2019-06-18T07:15:13.710701223Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2019-06-18T07:15:13.710714343Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.710726715Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2019-06-18T07:15:13.710739019Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.710751432Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.710763684Z 	at xorg.springboot.cors.CorsFilter.doFilter(CorsFilter.java:57)
2019-06-18T07:15:13.710775667Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.710788011Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.710801283Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
2019-06-18T07:15:13.710977369Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-06-18T07:15:13.710996268Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.711009326Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.711022243Z 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
2019-06-18T07:15:13.711034865Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-06-18T07:15:13.711050198Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.711063645Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.711076367Z 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
2019-06-18T07:15:13.711089189Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-06-18T07:15:13.711101739Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.711114481Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.711126935Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
2019-06-18T07:15:13.711139748Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-06-18T07:15:13.711152192Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2019-06-18T07:15:13.711165212Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2019-06-18T07:15:13.711177602Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
2019-06-18T07:15:13.711190235Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2019-06-18T07:15:13.711202677Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
2019-06-18T07:15:13.711215321Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2019-06-18T07:15:13.711227891Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
2019-06-18T07:15:13.711240476Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2019-06-18T07:15:13.711252814Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
2019-06-18T07:15:13.711265401Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
2019-06-18T07:15:13.711277691Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
2019-06-18T07:15:13.711290284Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
2019-06-18T07:15:13.711341410Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
2019-06-18T07:15:13.711362581Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2019-06-18T07:15:13.711378719Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2019-06-18T07:15:13.711392303Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2019-06-18T07:15:13.711404988Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2019-06-18T07:15:13.711418695Z 	at java.lang.Thread.run(Thread.java:745)

**期望的结果**
我希望最好能不报错

**Comment by liaochong** [comment]
是否必现？调用什么方法出现的？

**Comment by pangqibao** [comment]
> 是否必现？调用什么方法出现的？

不是必现的，我调用的是 AttachmentExportUtil.export(workbook, "调价商品", response);

**Comment by liaochong** [comment]
数据量有多少？

**Comment by pangqibao** [comment]
> 数据量有多少？
还好，不多，也就1234条数据

**Comment by liaochong** [comment]
这个问题一下子没找到原因，会尽快解决，从反馈来说不影响具体使用

**Comment by pangqibao** [comment]
> 这个问题一下子没找到原因，会尽快解决，从反馈来说不影响具体使用

嗯，不影响使用，只是报个错不太爽，哈哈，好的
